Model fallback for e-uniquac
ESSS/reaktoro pull request #7
Opened 2022-04-29 21:21 UTC by caiofcm

Two features were implemented:

- Only calculating short-range contribution for species with e-uniquac parameters available
- Options to select the long-range model. 
  - Original Thomsen DH
  - DH model using PHREEQC parameters (using the existing model in reaktoro)

Because the existing model was used, few adjustments were needed. For instance, e-uniquac operates using mol fraction scale. Only at the end the scale is changed to molality. Therefore, I changed the scale of DH using phreeqc to mol scale. Such that at the end of the e-uniquac model it will be added to the short-range contribution (in mol scale) and later will be converted to molalility scale.

There are some questions in the comments to be discussed.

2022-05-11 23:22 UTC, volpatto requested changes
Amazing work, @caiofcm! Great feature! I made some comments and suggestions to improve a bit some parts of the code.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +        {
We could remove these brackets in the `case`s since we do not have to worry about variable shadowing between the cases, i.e., the local scopes between the cases are not necessary.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    // TODO: Place in separated file as a regular factory of model function?
I think that it is fine to have it here since it is particular to E-UNIQUAC only. We can go as it is right now.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    switch(longRangeModelType)
What about a default option? It could be `modelLongRangeThomsen`, IMHO. It is usual for `switch` structure to have a `default` in order to avoid unexpected behaviors.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +        // for (const auto& i : indexSpeciesWithParams)
Commented code.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +        // for(const auto& i : indexSpeciesWithParams)
Commented code.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +        //     for (Index j = 0; j < num_species; ++j)
Commented code.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +        // for (Index i = 0; i < num_species; ++i)
Commented code.

2022-05-11 23:22 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    case LongRangeModelType::DH_Phreeqc:
Is this case correct?

2022-05-11 23:23 UTC, volpatto commented
It would be nice if @tadeu could also give a hand here.

2022-05-12 14:13 UTC, caiofcm commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    std::vector<std::string> speciesNames = mixture.namesSpecies();
Nice tip. Thank you!

2022-05-12 17:34 UTC, caiofcm commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    // std::vector<AqueousSpecies> speciesWithParams;
My bad for all these leftover commented codes

2022-05-12 17:44 UTC, caiofcm commented on tests/test_euniquacparams.py
> +    expected_mols = [5.55084350e+01, 5.20522014e-08, 5.20522014e-08, 6.18999020e+00, 6.18999020e+00, 9.38100098e+01]
Well, this case tests if the result with the modifications matches the results from the previous version. Hence, I collected these values from the fb-long-lived branch. When all species are known, e.g. have associated e-uniquac parameters, the results should be the same to the previous version.

2022-05-12 17:51 UTC, caiofcm commented on tests/test_euniquacparams.py
> +    assert True  # As the internal value (not necessary) is not exposed in the API I cannot assert
I am testing the function to set the type of the long range model. The best approach would be to confirm if the internal value of the `longRangeModelType` is set (in this case) to `DH_Preeqc`. However, this property is not accessible to the python API. I did not need to expose it, only for this particular test case. So, in this test I am only testing that no exception is raised.
I will just delete the `assert True` line in the future commit, but I am open to suggestions.

2022-05-12 18:24 UTC, caiofcm commented on tests/test_euniquacparams.py
> +    assert True  # As the internal value (not necessary) is not exposed in the API I cannot assert
I am testing the function to set the type of the long range model. The best approach would be to confirm if the internal value of the `longRangeModelType` is set (in this case) to `DH_Preeqc`. However, this property was not accessible to the python API. I did not need to expose it, only for this particular test case. In the next commit I will expose the `useLongRangeModelType` such that this can be properly tested (also it may be useful for other use cases)

2022-05-12 18:25 UTC, caiofcm commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.hpp
> +    auto useLongRangeModelType() const -> LongRangeModelType;
Ok, I was thinking that the use prefix was a convention (as is employed in `useDebyeHuckelGenericParameterA`)

2022-05-12 18:31 UTC, caiofcm commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    case LongRangeModelType::DH_Phreeqc:
Not sure if I understood. But I think it is correct. Could not found the issue. I want to use `convertLongRangeToMolScale  = true` for both DH_Phreeqc and HKF

2022-05-17 17:00 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
>      // Collect the UNIQUAC parameters r_i and q_i of the all species
```suggestion
    // Collect UNIQUAC parameters `r_i` and `q_i` of all species with known parameters.
```

2022-05-17 17:01 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    // TODO: Place in separated file as a regular factory of model function?
I agree, it's better to keep it all in one place for now, the TODO can be removed.

2022-05-17 17:04 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    PhaseChemicalModel modelLongRange;
Minor, perhaps it'd be more consistent to call the variable "long range model" instead of "model long range".

2022-05-17 17:07 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    switch(longRangeModelType)
The best is to use a `default:` throwing an exception, as a guard for when the `enum` is expanded to include more models but then someone forgets to update the `switch`es.

2022-05-17 17:11 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +        pimpl->convertLongRangeToMolScale = false;
Question: instead of the extra complication of handling different scales for different models, could we change the implementation of E-UNIQUAC models so that they are all using the same scale for ln γ as other models (DH, HKF)?

2022-05-17 17:15 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +            const auto i_index = indexSpeciesWithParams[i];
`mixture_index` perhaps would be more clear than `i_index` here.

2022-05-17 17:21 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    const Index num_species_known = indexSpeciesWithParams.size();
An `Assert` here that `waterIndexInKnowns` was found (and is not the initial invalid value) would be more robust than the assert on line 134.

2022-05-17 17:23 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +                ln_g[ispecies] = ln_g[ispecies] - ln_xw;
Question, just to know better: is this what Reaktoro usually does in other places?

2022-05-18 19:59 UTC, caiofcm commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.hpp
> +    auto setLongRangeModelType(const LongRangeModelType& longRangeModelType) -> void;
It requires adding `.export_values();` ([ref](https://pybind11.readthedocs.io/en/stable/classes.html#enumerations-and-internal-types)) to the `_enum` export

2022-05-18 20:10 UTC, tadeu commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.hpp
> +    auto setLongRangeModelType(const LongRangeModelType& longRangeModelType) -> void;
Hmm, weird, seems like a `pybind11` limitation then. If `pybind11` is "complaining" via compiler errors, no worries, it was just a minor thing.

2022-05-24 20:11 UTC, volpatto commented on Reaktoro/Thermodynamics/Models/AqueousChemicalModelEUNIQUAC.cpp
> +    // }
Commented code. I think we can drop it.

2022-05-24 20:14 UTC, volpatto commented on tests/test_euniquac_chemicalmodel.py
> +    # euniquac_params.setVillafafilaGarcia2006()  # very important!
I think I don't get it, my bad. Is it important to not use `setVillafafilaGarcia2006` here? Or could we drop the commented code here?

2022-05-25 12:30 UTC, tadeu commented on tests/test_euniquac_chemicalmodel.py
> +    # euniquac_params.setVillafafilaGarcia2006()  # very important!
Well noted

2022-05-25 12:30 UTC, tadeu commented on tests/test_euniquac_chemicalmodel.py
> +# @pytest.mark.parametrize(
Task: remove code comments

2022-07-01 16:20 UTC, merged